### ISSUE TITLE
npm error while installing mapic on Mac 

### ISSUE THREAD

**Issue by netfish88** [mapic/mapic#1]
Hi, I am interested in mapic solution.
I am trying to run it on my Mac, but there is a error while I am doing _npm install_ 

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! gdal@0.4.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gdal@0.4.3 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gdal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gdal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gdal
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/DavidHong/WebstormProjects/2016/mapic/npm-debug.log

any hint or tip for it? 
or is there a updated version of package.json ? (looks little bit outdated when I checked with _ncu_)

**Comment by netfish88** [comment]
the reason was that gdal cannot be installed node ver 6.x, only support 4.x LTS version.
and 0.4.3 has an error on mac, so need to upgrade 0.9.3 which is lastest version so far. 

check this issue 
https://github.com/mapbox/node-srs/issues/61
https://github.com/naturalatlas/node-gdal/issues/168

**Comment by knutole** [comment]
hi @netfish88 . actually, i don't think you'll be able to run `mapic` on localhost right now, it's part of a Docker Compose setup, which I haven't had time to release. 

Will ping you here when I've done so! :)

**Comment by netfish88** [comment]
@knutole thanks. I appriciate it. 
and I'd like to try the mapic.js too. can't wait it :)
