### ISSUE TITLE
Automate starting localhost server

### ISSUE THREAD

**Issue by knutole** [mapic/mapic#1]
### Automate setting up `localhost` server

This script will be used for `CI` also. Starting point is [`install-to-localhost.sh`](https://github.com/mapic/mapic/blob/master/install-to-localhost.sh).

should include: 
- [ ] install of latest version of Docker and Docker Compose
- [x] download of repos (mapic, mile, engine, config-localhost)
- [x] download of docker images from docker hub (not build)
- [x] setting of `ENV`
- [x] ensuring `npm modules` are installed correctly
- [x] creating self-signed ssl
- [x] opening/editing necessary configs (engine/mile/redis/mongo)
- [x] automatically set strong, unique passphrases for redis/mongo
- [x] create the first user and make super
- [x] run tests when it's set up!

Script should contain everything needed to go from _nothing_ to having a fully working running Mapic Engine server, ready to open browser @ https://localhost.

**Comment by knutole** [comment]
@destromas The migration from https://github.com/systemapic to https://github.com/mapic is done. We should therefore _only_ use https://github.com/mapic repos from here on.

I suggest you delete all your local repos (but save your scripts!), and pull a fresh repo from https://github.com/mapic/mapic:
```bash
git clone git@github.com:mapic/mapic.git
cd mapic
./install-to-localhost.sh
```

This will download all repos. Then you can add the configuration script to the `install-to-localhost.sh` script there.

**Comment by knutole** [comment]
@destromas1 Also, the config names have changed. (wu-config.js -> engine.config.js, pile-config.js -> mile.config.js), and needs to be updated in the script. 

See https://github.com/mapic/config-localhost/tree/master/localhost

**Comment by destromas1** [comment]
@knutole got that .Thanks!

**Comment by knutole** [comment]
This is now working, closing.
