### ISSUE TITLE
Custom built mapic/mongo:latest fails to authenticate mapic_mongo_user

### ISSUE THREAD

**Issue by mirzahusadzic** [mapic/mapic#18]
If one builds _mapic/mongo_  (a file _**docker/build/mongo/build.sh**_) from _mongo:latest_ (current version is v3.4.2) the _mapic_mongo_user_ fails to authenticate with error message:

**mongo_1        | 2017-03-29T16:42:28.338+0000 I ACCESS   [conn1] SCRAM-SHA-1 authentication failed for mapic_mongo_user on mapic from client 172.17.0.8:53292 ; AuthenticationFailed: SCRAM-SHA-1 authentication failed, storedKey mismatch**

Possible solution:

Current file _**docker/build/mongo/init_mongo.js**_ deletes _authSchema_ and inserts new one in order to downgrade it. It seems that the code has become obsolete and cause problems with new versions.

```
- admin.system.version.remove({})
- admin.system.version.insert({ '_id' : 'authSchema', 'currentVersion' : 3 })
```
By removing the code one should rebuild the image and the mongo user authenticate successfully.

**mongo_1        | 2017-03-29T17:07:06.022+0000 I ACCESS   [conn1] Successfully authenticated as principal mapic_mongo_user on mapic**

**Comment by knutole** [comment]
Hi Mirza. Thanks a lot for your feedback. Indeed this is a problem, but I was not aware of the solution in regards to new versions. 

Have you tested this solution? Does it also work with existing databases (ie. `mongo_store` image that's been initialized on a different Mongo version)? If you, I'd be happy to accept a PR. 

Thanks for participating and taking the time to report issues!

**Comment by mirzahusadzic** [comment]
Hi Knut, 

yes I tested the solution and it works, but just in this case (reported issue).
The case is covered in https://docs.mongodb.com/manual/release-notes/3.0-scram/

#
If you are starting with a new 3.0 installation without any users or upgrading from a 2.6 database that has no users, to use SCRAM-SHA-1, no user data upgrade is required. All newly created users will have the correct format for SCRAM-SHA-1.
#

To answer you question, I think that all depends on authorization schema database uses (Mongo version), so each case should be treated specifically and no universal script could/should cover it; for example if I migrate from initialized Mongo 2.6 to latest I may need to upgrade authorization schema with

``` javascript
admin.adminCommand({authSchemaUpgrade: 1});
```
See more at https://docs.mongodb.com/manual/release-notes/3.0-scram/#upgrade-mongodb-cr-to-scram

Thanks, I will create PR.
