### ISSUE TITLE
New Layer Types: GeoJSON / WMS

### ISSUE THREAD

**Issue by knutole** [mapic/mapic#67]
## Layer types
- [ ] M.Layer.GeoJSON 
- [ ] M.Layer.WMS

### Upload of GeoJSON file
- [ ] upload geojson in GUI or API directly
- [ ] lint geojson
- [ ] PostGIS or static file..

### Styling
- [ ] styling of GeoJSON in Style Editor
- [ ] styling of WMS in Style Editor ?? 
- [ ] is styling of WMS needed?

### Models
- [ ] create M.Layer.GeoJSON model
- [ ] create M.Layer.WMS model
- [ ] in `engine` and `mile`

### WMS
- [ ] create layer in GUI/API
- [ ] add/edit WMS details directly
- [ ] complexity of WMS data? string-based.

### Layer ordering 
Currently layer ordering is based on order of activation of layers in LayerMenu
- [ ] refactor layer menu
- [ ] create new controller for layer ordering
- [ ] save layer ordering in project model
- [ ] GUI for layer ordering

### Support HTML in tooltip
- [ ] add support for html in Leaflet tooltips.
- [ ] pull tooltip data directly from GeoJSON properties
- [ ] lint HTML

**Comment by knutole** [comment]
## Questions
### WMS
- [ ] What kind of WMS are you planning on using, what complexity level? (WFS or only WMS? Single-layer or multi-layers?)
- [ ] Do you need query capabilities for WMS, or just map tiles?
- [ ] What are your WMS sources? Examples? What's the use-case?
- [ ] Do you need to be able to style the WMS? (I'm not so familiar with WMS styling, but need to know what your needs are.)

### GeoJSON
- [ ] What's the use-case?
- [ ] Full styling capabilites needed?

**Comment by rexso** [comment]
Does it matter what WMS source is used if the protocol standard is supported?
